package JSCompile.formatters;

import JSCompile.domain.JSArtifact;

import java.util.ArrayList;

public class Concatenator {

    private StringBuilder source = null;
    private boolean exported = false;

    public Concatenator(String packageName, ArrayList<String>namespaces){
        this.source = new StringBuilder();
        writeHeader(packageName);
        writeNamespaces(namespaces);
    }


    public void add(JSArtifact artifact){
        if(!exported){
            writeNamespaceMemberDefinition(artifact.getNamespace(), artifact.getName(), artifact.dependencies, artifact.getSource());
        }

    }

    public String export(){
        writeFooter();
        return source.toString();
    }





    private void writeIndent(){
        source.append("    ");
    }

    private void writeIndent(int numberOfIndents){
        for(int i=0; i<numberOfIndents; i++){
            writeIndent();
        }
    }

    private void writeHeader(String packageName){
        source.append("// Generated by JSCompile (https://github.com/rliota/JSCompile) on ");
        source.append(new java.util.Date());
        source.append("\n");
        source.append("function initialize");
        source.append(packageName);
        source.append("(){\n");
    }

    private void writeNamespaces(ArrayList<String> namespaceList){
        for(String namespace : namespaceList){
            writeIndent();
            source.append(namespace);
            source.append(" = {};\n");
        }
        source.append("\n");
    }

    private void writeNamespaceMemberDefinition(String namespace, String memberName, ArrayList<String> dependencies, String memberSource){
        writeIndent();
        source.append(namespace);
        source.append(".");
        source.append(memberName);
        source.append(" = (function(");
        int dependenciesLength = dependencies.size();
        for(int i=0; i<dependenciesLength; i++){
            if(i>0){
                source.append(", ");
            }
            String dependencyNamespace = dependencies.get(i);
            String[] dependencyPackageParts = dependencyNamespace.split(".");
            source.append(dependencyPackageParts[dependencyPackageParts.length-1]); // There is no good reason a null pointer exception should occur here.
        }
        source.append("){\n");
        source.append(memberSource);
        writeIndent();
        source.append("\n}(\n");

        for(String dependencyNamespace : dependencies){
            writeIndent(2);
            source.append(dependencyNamespace);
            source.append("\n");
        }

        writeIndent();
        source.append("));\n\n");
    }

    private void writeFooter(){
        source.append("}");
    }

}
